# NumPy

NumPy is a library for the Python adding support for large, multi-dimensional arrays, along with a large collection of high-level mathematical functions to operate on these arrays. 


NumPy array can represent any multidimentional arrays but all elements must be of same type. If not all inputs are of same type then, all elements are promoted to type which can represent all elements if possible.

In [1]:
import numpy as np


### Basic information about numpy array

In [2]:
a = np.arange(24).reshape(2,3,4)
print("a =\n", a, "\n")
print("Number of elements in array \ta.size =", a.size)
print("Number of Dimentions \t\ta.ndim =", a.ndim)
print("Number of elements in each dimention \ta.shape =", a.shape)
print("Datatype of elements \t\ta.dtype.name =", a.dtype.name)
print("Datatype of elements \t\ta.dtype =", a.dtype)
print("size of each element in Bytes \ta.itemsize =", a.itemsize)
print("data type of a \t\t\ttype(a) =", type(a))


a =
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

Number of elements in array 	a.size = 24
Number of Dimentions 		a.ndim = 3
Number of elements in each dimention 	a.shape = (2, 3, 4)
Datatype of elements 		a.dtype.name = int32
Datatype of elements 		a.dtype = int32
size of each element in Bytes 	a.itemsize = 4
data type of a 			type(a) = <class 'numpy.ndarray'>


### Creating numpy array

In [3]:
# Creating one dimentional array
b1 = np.array([1, 2, 3, 4])    # list
b2 = np.array((5, 6, 7, 8))    # tuple
print("b1 =", b1)
print("b2 =", b2)

# Creating two dimentional array with python list
b3 = np.array([[1, 2, 3, 4], (5, 6, 7, 8)])    # one list and one tuple
print("b3 =\n", b3)

# Creating numpy array with numpy arrays
b4 = np.array([b1, b2])
print("b4 =\n", b4)

l5 = [1.1, 2, 3, 4]
b5 = np.array(l5)    # from list
print("l5 =", l5)
print("b5 =", b5)


b1 = [1 2 3 4]
b2 = [5 6 7 8]
b3 =
 [[1 2 3 4]
 [5 6 7 8]]
b4 =
 [[1 2 3 4]
 [5 6 7 8]]
l5 = [1.1, 2, 3, 4]
b5 = [1.1 2.  3.  4. ]


In [4]:
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than or equal to 18
print(my_house >= 18)

# my_house less than your_house
print(my_house < your_house)

# my_house greater than 18.5 or smaller than 10
print(np.logical_or(my_house>18.5, my_house<10))

# Both my_house and your_house smaller than 11
print(np.logical_and(my_house<11, your_house<11))


[ True  True False False]
[False  True  True False]
[False  True False  True]
[False False False  True]


In [5]:
both_house = np.array([my_house, your_house])
print("both_house =\n", both_house)
for ar in np.nditer(both_house):
    print(ar)

both_house =
 [[18.   20.   10.75  9.5 ]
 [14.   24.   14.25  9.  ]]
18.0
20.0
10.75
9.5
14.0
24.0
14.25
9.0
