# NumPy Functions

In [1]:
import numpy as np


### np.random.random(): Create array with random numbers

In [2]:
np.random.random((2,2))

array([[0.52487956, 0.8357394 ],
       [0.22638036, 0.11124882]])

### np.zeros / np.ones / np.full: Create array filled with zeros/ones/fill_value

In [3]:
z = np.zeros([3])  # Default dtype float64
print(z)
z = np.ones([3])
print(z)
z = np.full([3], 5)
print(z, end='\n\n')

z = np.zeros([2, 5], dtype=np.int8)
print(z)

[0. 0. 0.]
[1. 1. 1.]
[5 5 5]

[[0 0 0 0 0]
 [0 0 0 0 0]]


### np.zeros_like / np.ones_like / np.full_like: Create array filled with zeros/ones/fill_value with shape of argument array

In [4]:
z = np.zeros_like(z)  # Default dtype float64
print(z)
z = np.ones_like(z)
print(z)
z = np.full_like(z, 5)
print(z, end='\n\n')


[[0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[5 5 5 5 5]
 [5 5 5 5 5]]



### np.identity / np.eye: Create identity array.


In [5]:
print(np.identity(3))
np.eye(2, 3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.]])

### np.arange() / np.linspace(): Create arithmetic progression

In [6]:
n = np.arange(5)
print(n)
n = np.arange(5, 10)
print(n)
n = np.arange(0.0, 1.0, 0.1)
print(n)
n = np.arange(0.0, 1.0, 0.2, dtype=np.float_)
print(n)


[0 1 2 3 4]
[5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.2 0.4 0.6 0.8]


In [7]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## Methods on ndarray instances 

### A.astype(T)
Creates a new array with the elements from A, but as type T

In [8]:
s1 = np.arange(5, 10)
print(s1)

s2 = s1.astype(np.float_)
print(s2)

[5 6 7 8 9]
[5. 6. 7. 8. 9.]


### A.copy() : Deep copy
Creates a new ndarray as an exact copy of A

In [9]:
s3 = s2.copy()
s2[2] = 73.88
print(s2)
print(s3)

[ 5.    6.   73.88  8.    9.  ]
[5. 6. 7. 8. 9.]


### A.reshape(dims)
Returns a NEW array that is a copy of the values A but having a shape given by dims.

In [10]:
a1 = np.arange(1., 11., 1.0)
print(a1)
a2 = a1.reshape( (2,5) )
print(a2)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


### A.resize(dims)
Changes the shape of array A, but does so in place.


In [11]:
print(a1)
a1.resize([2,5])
print(a1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


### A.mean()
Returns the mean of the values in A.

In [12]:
print(a1.mean())

5.5


### A.var()
Returns the variance of the values in A.

In [13]:
print(a1.var())

8.25


### Mathematical operators (+, -, *, /) 

For these operator to work, dimentions of the arrays must match.
When one of the operand is a constant, it is broadcased and operation is performed on every element of an array. This is called broadcasting.


In [14]:
v1 = np.arange(0.6, 1.6, 0.1)
print(v1)
v2 = np.arange(40.0, 50.0, 1.0)
print(v2, end='\n\n')

print(v1**2)
print(v1+v2)
print(v1-v2)
print(v1*v2)
print(np.multiply(v1, v2), end='\n\n')

print(v1)
print(v1 + 0.4)
print(v1 * 10)
print(v1*10+100)


[0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5]
[40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]

[0.36 0.49 0.64 0.81 1.   1.21 1.44 1.69 1.96 2.25]
[40.6 41.7 42.8 43.9 45.  46.1 47.2 48.3 49.4 50.5]
[-39.4 -40.3 -41.2 -42.1 -43.  -43.9 -44.8 -45.7 -46.6 -47.5]
[24.  28.7 33.6 38.7 44.  49.5 55.2 61.1 67.2 73.5]
[24.  28.7 33.6 38.7 44.  49.5 55.2 61.1 67.2 73.5]

[0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
[ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[106. 107. 108. 109. 110. 111. 112. 113. 114. 115.]


### Universal functions

Function Name | Description
:--|:--
np.abs(a)|Absolute value.
np.sqrt(a)|Square root.
np.exp(a)|Exponential, e^a.
np.log(a)|Natural log.
np.log10(a)|Common log (base 10).
np.sin(a)|Sine.

In [15]:
print(np.abs(np.arange(-4, 5)))
print(np.exp(np.arange(0, 5)))
angles = np.arange(0.0, np.pi*9.0/4.0, np.pi/4.0)
print(angles/np.pi)
print(np.sin(angles))


[4 3 2 1 0 1 2 3 4]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]


### Dot and cross products

In [16]:
a1 = np.array([[1, 2, -4], [3, -1, 5]])
a2 = np.array([[6, -3], [1, -2], [2, 4]])
print(a1)
print(a2)
print(np.dot(a1, a2))

x = (1, 2, 0)
y = (4, 5, 6)
print(np.cross(x, y))

[[ 1  2 -4]
 [ 3 -1  5]]
[[ 6 -3]
 [ 1 -2]
 [ 2  4]]
[[  0 -23]
 [ 27  13]]
[12 -6 -3]


## Linear algebra functions


### np.linalg.det(a)
Returns the determinant of a 2-d array a


In [17]:
m = np.array(((2,3), (-1, -2)))
print(m)
print(np.linalg.det(m))

[[ 2  3]
 [-1 -2]]
-1.0


### np.linalg.inv(a)
Returns the matrix inverse of a non-singular 2-d array a.


In [18]:
good = np.array(((2.1, 3.2), (4.3, 5.4)))
print(np.linalg.inv(good))

[[-2.23140496  1.32231405]
 [ 1.7768595  -0.8677686 ]]


### np.linalg.norm(a)
Returns the Frobenius norm of array a.


In [19]:
print(good)
print(np.linalg.norm(good))

[[2.1 3.2]
 [4.3 5.4]]
7.893034904268447


### np.linalg.solve(A, b)
Solves systems of simultaneous linear equations. Given an N×N array of coefficients A, and a lengthN vector of constants b, returns a length-N vector containing the solved values of the variables.
For example

2x + y = 19

x - 2y = 2


In [20]:
coeffs = np.array([[2,1], [1,-2]])
print(coeffs)
consts = np.array((19, 2))
print(consts)
print(np.linalg.solve(coeffs, consts))

[[ 2  1]
 [ 1 -2]]
[19  2]
[8. 3.]


In [21]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])